### ISSUE TITLE
Latest @octokit/rest has a .graphql method so no need to add it

### ISSUE THREAD

**Issue by gr2m** [JasonEtco/actions-toolkit#108]
Latest `@octokit/rest` is built on `@octokit/core`, so when you update you can remove your workaround

https://github.com/JasonEtco/actions-toolkit/blob/5c38cd50824e1de264d95bef64324f1d12b7bb59/src/github.ts#L4-L13

But I'm also not sure why you keep exposing that API instead of telling people how to load their own octokit instance. It will reduce your maintenance and support overhead, and there is maybe one extra line of code for the users

**Comment by JasonEtco** [comment]
Ah that's great to know! Hopefully I'll be able to make that change in the next release. FYI, I wasn't able to upgrade to v17 because of type issues that I was planning to talk to you about; but now those probably aren't an issue, because it was while extending to add `.graphql`!

> But I'm also not sure why you keep exposing that API instead of telling people how to load their own octokit instance. It will reduce your maintenance and support overhead, and there is maybe one extra line of code for the users

This is a hill I'm actually prepared to die on - its a part of Probot that I really love, and that I think makes using it far simpler. That's my personable opinion, but it's also part of why this library is more "opinionated" than not.
