### ISSUE TITLE
Stop warning about `HOME` not being present on Windows runners

### ISSUE THREAD

**Issue by EndBug** [JasonEtco/actions-toolkit#160]
As of now, the toolkit is creating a warning every time the `HOME` env variable is not present, as it's part of the required env variables:
https://github.com/JasonEtco/actions-toolkit/blob/c6c7208c521db3b7418dbc9cf5eab282a501250e/src/index.ts#L264-L274

A user of mine has reported [here](https://github.com/EndBug/add-and-commit/issues/516) that Windows runners don't use the `HOME` variable, even if they are original runners from GitHub.

I think the `HOME` variable could be removed from the list, since it doesn't seem to be actually used by the toolkit. Also, if one really needed to work with paths, there are a lot of other variables that GitHub provides in their runners, like: `GITHUB_WORKSPACE`, `GITHUB_ACTION_PATH`, `GITHUB_EVENT_PATH`, `GITHUB_PATH`, ...

**Comment by cliffchapmanrbx** [comment]
I can confirm that my company has been using your GHA workflow and we have been seeing this warning for quite some time :) 

It looks like [the HOME env var is not used for anything other than tests](https://github.com/search?q=repo%3AJasonEtco%2Factions-toolkit+HOME&type=code). Indeed some time ago [explicitly failing on missing env vars was reverted](https://github.com/JasonEtco/actions-toolkit/issues/38#issuecomment-477863998) because valid GitHub envs omitted some of the list.

It seems like dropping HOME from that list would be safe to do, provided the tests were updated to alter a different expected env var.

**Comment by EndBug** [comment]
Yup

**Comment by EndBug** [comment]
But I did comment!
>:|
